"""错误码与统一异常(设计文档第 20 节)。"""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    AUTH_CONFIRM_REQUIRED = "AUTH_CONFIRM_REQUIRED"
    BROWSER_NOT_INSTALLED = "BROWSER_NOT_INSTALLED"
    BROWSER_PROFILE_LOCKED = "BROWSER_PROFILE_LOCKED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    LOGIN_TIMEOUT = "LOGIN_TIMEOUT"
    LOGIN_SESSION_EXPIRED = "LOGIN_SESSION_EXPIRED"
    CAPTURE_NO_MEDIA_REQUEST = "CAPTURE_NO_MEDIA_REQUEST"
    CAPTURE_MULTIPLE_CANDIDATES = "CAPTURE_MULTIPLE_CANDIDATES"
    CAPTURE_RESPONSE_INVALID = "CAPTURE_RESPONSE_INVALID"
    AUTH_CONTEXT_INCOMPLETE = "AUTH_CONTEXT_INCOMPLETE"
    INPUT_INVALID = "INPUT_INVALID"
    PLAYLIST_HTTP_401 = "PLAYLIST_HTTP_401"
    PLAYLIST_HTTP_403 = "PLAYLIST_HTTP_403"
    PLAYLIST_URL_EXPIRED = "PLAYLIST_URL_EXPIRED"
    PLAYLIST_INVALID = "PLAYLIST_INVALID"
    MASTER_NO_VARIANT = "MASTER_NO_VARIANT"
    METHOD_UNSUPPORTED = "METHOD_UNSUPPORTED"
    KEYFORMAT_UNSUPPORTED = "KEYFORMAT_UNSUPPORTED"
    KEY_HTTP_ERROR = "KEY_HTTP_ERROR"
    KEY_LENGTH_INVALID = "KEY_LENGTH_INVALID"
    SEGMENT_HTTP_ERROR = "SEGMENT_HTTP_ERROR"
    CIPHERTEXT_BLOCK_INVALID = "CIPHERTEXT_BLOCK_INVALID"
    DECRYPT_PADDING_INVALID = "DECRYPT_PADDING_INVALID"
    DECRYPT_MEDIA_INVALID = "DECRYPT_MEDIA_INVALID"
    BYTERANGE_UNSUPPORTED = "BYTERANGE_UNSUPPORTED"
    DISCONTINUITY_COMPLEX = "DISCONTINUITY_COMPLEX"
    REFRESH_MEDIA_MISMATCH = "REFRESH_MEDIA_MISMATCH"
    AUTH_REFRESH_LIMIT_REACHED = "AUTH_REFRESH_LIMIT_REACHED"
    FFMPEG_FAILED = "FFMPEG_FAILED"
    FFMPEG_NOT_FOUND = "FFMPEG_NOT_FOUND"
    OUTPUT_DURATION_MISMATCH = "OUTPUT_DURATION_MISMATCH"
    OUTPUT_NO_VIDEO = "OUTPUT_NO_VIDEO"
    URL_EXPIRED_DURING_JOB = "URL_EXPIRED_DURING_JOB"
    LIVE_PLAYLIST_UNSUPPORTED = "LIVE_PLAYLIST_UNSUPPORTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class PocError(Exception):
    """带错误码的 PoC 异常。message 必须已脱敏。"""

    def __init__(self, code: ErrorCode, message: str, *, hint: str | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.hint = hint

    def to_dict(self) -> dict:
        return {"code": self.code.value, "message": self.message, "hint": self.hint}
